### ISSUE TITLE
Nexus 6, Android 6.0 Upside-Down & Corrupt Stream

### ISSUE THREAD

**Issue by nick-fedesna** [NodeMedia/NodeMediaClient-Android#11]
Google Nexus 6 (and 6P) running Android 6.0 (Marshmallow): front-camera preview is upside-down and the stream is 100% green.  Upgrading to Android 7.0 does fix but not ideal solution.  But present since v1.0

**Comment by illuspas** [comment]
This problem requires a real machine to debug.	
I just bought it.On the way.

**Comment by illuspas** [comment]
Please test version v1.2.8
