### ISSUE TITLE
No RECORD_AUDIO permission results in green stream

### ISSUE THREAD

**Issue by nick-fedesna** [NodeMedia/NodeMediaClient-Android#12]
On Android 6.0+ if user does not granted RECORD_AUDIO permission the resulting stream is green.  Even if `setMicEnable(false)` is called before `startPreview()`, the stream is green color.

I believe the cause is because it is not reaching the `setCameraParm(…)` call if AudioRecorder initialization returns `-1` in `LivePublisher.startPreview()`.

**Comment by illuspas** [comment]
v1.2.8 fix this problem.

**Comment by nick-fedesna** [comment]
confirmed, fixed in 1.2.8, thank you
