### ISSUE TITLE
1.2.9版本串流功能咨询

### ISSUE THREAD

**Issue by tc214** [NodeMedia/NodeMediaClient-Android#16]
请教一个问题，1.2.9版本串流功能咨询，输入地址和输出地址如何填写？我想播放本地视频文件，串流到同一个局域网下的其他手机上，需要RTMP服务器支持吗？  调试时总是出现：Could not open output url 'rtmp://192.168.1.218:1957/live/stream'

**Comment by illuspas** [comment]
RTMP是需要服务端的协议  
不过在最新的2.x版本里,NodePlayer实现了一个本地服务的功能 
setLocalRTMP ,只需要接收端开启,并播放一个地址就能开启服务,进行行监听
比如"rtmp://192.168.1.218:1957/live/stream"
这时候同局域网的另一个手机就可以用NodePublisher推流到这个手机的ip上来'rtmp://192.168.1.218:1957/live/stream'

或者用NodeStreamer串流文件过来也可以

**Comment by tc214** [comment]
Tks! 可否提供一下jar包呢？

**Comment by tc214** [comment]
@illuspas
楼主，你好！你在上面说的本地服务是不是需要在代码里开启？我看到最新的代码里有一行：np.setLocalRTMP(true);被注释掉了。

**Comment by illuspas** [comment]
这个功能当然是根据需要再开启了

**Comment by tc214** [comment]
@illuspas
楼主，我刚刚测试了一下串流功能，果然可以用，但是用NodeStreamer串流文件，只能发送部分文件，50秒长的MP4文件，收到的只有最后10秒。可否帮忙解决一下呢？

**Comment by tc214** [comment]
@illuspas
楼主，我刚刚测试了一下串流功能，果然可以用，但是用NodeStreamer串流文件，只能发送部分文件，50秒长的MP4文件，收到的只有最后10秒。可否帮忙解决一下呢？   另外，如果能像vlc的串流功能一样，加上本地显示就完美了。

**Comment by illuspas** [comment]
文件串流 用startNativeRateStreaming这个方法，相当于 ffmpeg加 -re 选项
