### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [NodeMedia/NodeMediaClient-Android#2]
Hi there, 1st of all thanks for this awesome work !

Since we've 'doxed' it in our [HyMPS project](https://forart.it/HyMPS) (under [VIDEO section](https://github.com/FORARTfe/HyMPS#-1 ) \ [RTSP page](https://github.com/FORARTfe/HyMPS/blob/main/Video/RTSP.md#-- ) \ [Android](https://github.com/FORARTfe/HyMPS/blob/main/Video/RTSP.md#android-)), can you please add a GH-compliant license file for it ?

As you know, expliciting licensing terms is extremely important to let anyone better/faster understand how to reuse/adapt/modify sources (and not only) in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://badgen.net/github/license/NodeMedia/NodeMediaClient-Android)
(badge-generator URL: https://badgen.net/github/license/NodeMedia/NodeMediaClient-Android)

You can easily set a standardized one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Hope that helps/inspires !

**Comment by fahimfahadleo** [comment]
![Screenshot from 2024-06-04 23-54-02](https://github.com/NodeMedia/NodeMediaClient-Android/assets/55629660/2cde277b-0d55-41b6-8478-182fb7b0f026)

**Comment by fahimfahadleon** [comment]
can not register

**Comment by fahimfahadleon** [comment]
I have created a license for my project in GH and put the url of the
license in the section NodePlayer node = new NodePlayer(this,URL); here.
but still getting node player unauthorized toast. is there another process
to do this?

**Comment by MarcoRavich** [comment]
> is there another process to do this?
>

Hi there, thanks for reply.

As said, the easiest way to do so is to use the GH license wizard tool.

The other way is to manually create a LICENSE.md file in your repo.

What license have you choosed for your project ?

**Comment by fahimfahadleo** [comment]
Nolicense

**Comment by MarcoRavich** [comment]
@fahimfahadleo ...there are many valid alternatives to "license unknown":
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

"Creative Commons Zero v1.0 Universal", "The Unlicense" or "Do What The F*ck You Want To Public License" - which are all recognized by GH - may fit your needs.
