### ISSUE TITLE
How to set VideoOrientation in NodeMediaClient 2.x library?

### ISSUE THREAD

**Issue by FAReact** [NodeMedia/NodeMediaClient-Android#20]
I try to use NodeMediaClient 1.x it has setVideoOrientation() metod. But when I use NodeMediaClient 2.x library I  can use setVideoOrientation() metod. Is the any other metod has for changeing VideoOrientation?

**Comment by illuspas** [comment]
The video output orientation automatically follows the interface layout orientation.
The orientation is locking in publish status.

**Comment by BestAndroidProgrammer** [comment]
Can I set landscape  (horizontal) oriantation for interface layout?
