### ISSUE TITLE
Change the audio sample rate from 44100 to 48000

### ISSUE THREAD

**Issue by Dayananda** [NodeMedia/NodeMediaClient-Android#21]
how to change audio sample rate 48000

**Comment by illuspas** [comment]
The current version does not support.

**Comment by Dayananda** [comment]
when can i expect this feature to be implemented?? I am student need to add the sample rate feature for final demo. Thanks

**Comment by illuspas** [comment]
2.3.0 already supported

**Comment by Dayananda** [comment]
Thanks for the support. after changing to 48000 audio is not clear it is giving jerk and lot of noise but with 44100 sample rate works fine. Any specific configuration I need to change??
