### ISSUE TITLE
How to start Demo Example.

### ISSUE THREAD

**Issue by kaushal2406** [NodeMedia/NodeMediaClient-Android#24]
Please give sample example code to start rtmp Url play in MainActivity given.
And other feature like 
zoom in / out 
voice Mute/unmute.
etc.

please give sample code for run android demo.

please mail me demo code in kaushal2406@gmail.com

**Comment by illuspas** [comment]
Please checkout '2.x' branch.
https://github.com/NodeMedia/NodeMediaClient-Android/tree/2.x

**Comment by kaushal2406** [comment]
thanks,
Demo Working fine.
I Need Zoom in /out button
orientation change button
