### ISSUE TITLE
android使用报错 A/libc: Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by vilianfung** [NodeMedia/NodeMediaClient-Android#33]
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 20866 (Thread-26), pid 20234 (.app.yichengpai)
请问这是什么问题，谢谢

**Comment by CocktailZY** [comment]
> A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 20866 (Thread-26), pid 20234 (.app.yichengpai)
> 请问这是什么问题，谢谢

请问你解决了吗？
