### ISSUE TITLE
How to set multiple live url to play 

### ISSUE THREAD

**Issue by Dayananda** [NodeMedia/NodeMediaClient-Android#34]
How to set multiple live url to play for smooth streaming?

When you guys are planning for HEVC encoding support in android?

**Comment by illuspas** [comment]
Buy the premium version of the license, we provide hardware accelerated decoding

**Comment by Dayananda** [comment]
How much does it cost??

**Comment by Dayananda** [comment]
waiting for your replay

**Comment by illuspas** [comment]
Please contact our business support: service@nodemedia.cn
