### ISSUE TITLE
Wowza Authentication

### ISSUE THREAD

**Issue by friman** [NodeMedia/NodeMediaClient-Android#4]
Hello!

I am interested to know how to setup an rtmp url with authentication, I had tried rtmp://username:password@wowza-address:port/live/streamname  and have not result. Is there some idea how to set up that?
Thanks on advance
Regards

**Comment by illuspas** [comment]
Sorry for late reply.The current version of this sdk does not support adobe auth.We will fix this problem in the next version.

**Comment by illuspas** [comment]
fix in v0.9.9

**Comment by friman** [comment]
Hello!
Thanks for your replies. Any idea when planning to launch this version?

**Comment by illuspas** [comment]
@friman 
https://github.com/NodeMedia/NodeMediaClient-Android/releases/tag/v0.9.9

**Comment by friman** [comment]
Hello! 
Thanks for your response once again
I had tested and it work perfect! Now another question regarding to authorization to use on other development, I sent message to your email. 

Regards
