### ISSUE TITLE
请问有水印功能吗

### ISSUE THREAD

**Issue by echo-cmh** [NodeMedia/NodeMediaClient-Android#43]

**Comment by lalaluya** [comment]
你好，你找到水印功能了吗？

**Comment by echo-cmh** [comment]
没有 后来取了视频流在后台的java代码里加的水印 或者在ng里也能加------------------ 原始邮件 ------------------
发件人: "wuxuesong"<notifications@github.com>
发送时间: 2019年11月4日(星期一) 上午9:27
收件人: "NodeMedia/NodeMediaClient-Android"<NodeMediaClient-Android@noreply.github.com>;
抄送: "echo-cmh"<460018463@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NodeMedia/NodeMediaClient-Android] 请问有水印功能吗 (#43)



你好，你找到水印功能了吗？
 
&mdash;

**Comment by lalaluya** [comment]
> 没有 后来取了视频流在后台的java代码里加的水印 或者在ng里也能加------------------ 原始邮件 ------------------ 发件人: "wuxuesong"<notifications@github.com> 发送时间: 2019年11月4日(星期一) 上午9:27 收件人: "NodeMedia/NodeMediaClient-Android"<NodeMediaClient-Android@noreply.github.com>; 抄送: "echo-cmh"<460018463@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [NodeMedia/NodeMediaClient-Android] 请问有水印功能吗 (#43) 你好，你找到水印功能了吗？ &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，谢谢
