### ISSUE TITLE
出现播放花屏和声音异常,用vlc试是可以的

### ISSUE THREAD

**Issue by NessCurie** [NodeMedia/NodeMediaClient-Android#46]
![image](https://user-images.githubusercontent.com/20910351/61762343-40191a80-ae04-11e9-8cbf-d54f246befa3.png)

**Comment by NessCurie** [comment]
换成最新版本的 用TCP可以正常显示不花屏了  但是声音还是解不出来

**Comment by lalaluya** [comment]
> 换成最新版本的 用TCP可以正常显示不花屏了 但是声音还是解不出来

你试试更改下包长
