### ISSUE TITLE
开始播放时，总是声音先出来，画面是黑屏

### ISSUE THREAD

**Issue by BaoTaoGitHub** [NodeMedia/NodeMediaClient-Android#49]
点播的时候，开始播放时，总是声音先出来，画面是黑屏，等几秒之后，画面才同步出来。请问大佬这个是为什么啊。

**Comment by 52yaoer** [comment]
我也一样，，

**Comment by illuspas** [comment]
sdk具有秒开能力，需要服务端配合，连上后马上有视频关键帧送来解码才能显示出画面。一般来说就是gop_cache功能。
音频每帧都可以直接解码，所以出现先有声音后后画面的情况。
