### ISSUE TITLE
SEI扩展数据 能支持吗

### ISSUE THREAD

**Issue by xjaksyt2008** [NodeMedia/NodeMediaClient-Android#50]
SEI扩展数据 播放端和推送端 能支持吗

**Comment by wangtaoT** [comment]
+1

**Comment by wangtaoT** [comment]
我已经实现的SEI插入功能->https://wangtaot.github.io/2020/06/03/Android%E6%8E%A8%E6%B5%81rtmp%E6%8F%92%E5%85%A5SEI/
