### ISSUE TITLE
OpenSSL 1.1.1 issue. Rejected by Google Play 

### ISSUE THREAD

**Issue by HotPixelChannel** [NodeMedia/NodeMediaClient-Android#78]
Hello. Google refuses to publish the application because the player library uses an old version of OpenSSL

![image](https://user-images.githubusercontent.com/95171611/198732860-9e8a9fe3-0459-469d-a7a0-bfe25125ccd8.png)

**Comment by umarrazzak0922** [comment]
Hi, I am also getting the same issue with this.My player has it as a core dependency and google play is rejecting this with an error saying **_Defective version of OpenSSL used 1.1.1g in lib/arm/64-v8a/libNodeMediaClient.so_**. 
Please help with this.

Thank you !

**Comment by illuspas** [comment]
Restoration work is already underway.

**Comment by baralgin1003** [comment]
> Hi, I am also getting the same issue with this.My player has it as a core dependency and google play is rejecting this with an error saying **_Defective version of OpenSSL used 1.1.1g in lib/arm/64-v8a/libNodeMediaClient.so_**. Please help with this. I am using react-native-video as the player for my application.
> 
> Thank you !

as a temporary solution, you can change the OpenSSL version in both files libNodeMediaClient.so with a hex editor   (1.1.1g to 1.1.1i and release date) . Google, apparently, determines the version by the text field, and not by the signature. it helped me to publish the application

**Comment by umarrazzak0922** [comment]
> Restoration work is already underway.
Appreciated !!! The quick response along with the hard work :-)

**Comment by umarrazzak0922** [comment]
> > Hi, I am also getting the same issue with this.My player has it as a core dependency and google play is rejecting this with an error saying **_Defective version of OpenSSL used 1.1.1g in lib/arm/64-v8a/libNodeMediaClient.so_**. Please help with this. I am using react-native-video as the player for my application.
> > Thank you !
> 
> as a temporary solution, you can change the OpenSSL version in both files libNodeMediaClient.so with a hex editor (1.1.1g to 1.1.1i and release date) . Google, apparently, determines the version by the text field, and not by the signature. it helped me to publish the application

Thanks @baralgin1003  for the temporary fix
