### ISSUE TITLE
No audio on live stream on latest version of this library React native

### ISSUE THREAD

**Issue by codal-mpawar** [NodeMedia/NodeMediaClient-Android#84]
@Adnan46 @illuspas @piggylaw @Speical 

https://github.com/NodeMedia/react-native-nodemediaclient 

hey, guys Please help us We are suffering from the audio issue on the live stream. Because the above plugin was archived by the owner we are not able to create issues with that. so that's why I am creating an issue here. If anyone has any solution please share it with us.

We are using this version of plugin **"react-native-nodemediaclient": "^0.2.18"** and in that android media client version is **implementation 'com.github.NodeMedia:NodeMediaClient-Android:2.9.16'**, in that audio, is coming. So in that OpenSSL issue occurs. but after that we create one patch file for that and replace **implementation 'com.github.NodeMedia:NodeMediaClient-Android:2.9.22'** now audio was not working.
 
 Let me know if you need more information guys. Please support us. we are block for release.

**Comment by codal-mpawar** [comment]
@illuspas Any update on this?

**Comment by viniciuseduardo** [comment]
@codal-mpawar Same issue in my app.

**Comment by illuspas** [comment]
Play stream no sound or push stream no sound ?

**Comment by illuspas** [comment]
It's already under development.
The first step is to fix the problems with the old SDK,
The second step will restart this project and update support to the latest react native.

**Comment by illuspas** [comment]
Updated to 2.9.23 to fix the problem.
