### ISSUE TITLE
Commercial version (player only)

### ISSUE THREAD

**Issue by AlexUrrutia** [NodeMedia/NodeMediaClient-Android#88]
Hello, how can I get a player library only? not sure on that, prices etc.
it says player will expire in 7 days, is that normal? what happens after 7 days?
Please let me know, thanks!

**Comment by illuspas** [comment]
It can only be integrated together, however a single so is not large.
And the armeabi-v7a,x86,x86_64 architecture can be excluded if necessary to reduce program size.

**Comment by AlexUrrutia** [comment]
app size is increased by 20+ MB
