### ISSUE TITLE
现在支持多画面的播放了吗

### ISSUE THREAD

**Issue by avsuper** [NodeMedia/NodeMediaClient-Android#9]
以前的版本是只能支持播放一路，新版本的可以同时播放多路了吗？

**Comment by illuspas** [comment]
可以了哟,用新的NodePlayer类,具体看[这个实现Demo](https://github.com/NodeMedia/NodeMediaClient-Android/blob/AS/app/src/main/java/cn/nodemedia/nodemediaclient/NodePlayerDemoActivity.java)
